### ISSUE TITLE
Errors during creation of new LetsEncrypt account via acme.

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-pki#124]
This is the actual error:
<pre>
$ cat /etc/pki/realms/REALM/acme/error.log             
Parsing account key...                                                         
Parsing CSR...                                                                 
Found domains: domain.ex                                            
Getting directory...                                                           
Directory found!                                                               
Registering account...                                                         
Traceback (most recent call last):                                             
  File "/usr/local/lib/pki/acme-tiny", line 197, in <module>                   
    main(sys.argv[1:])                                                         
  File "/usr/local/lib/pki/acme-tiny", line 193, in main                       
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/local/lib/pki/acme-tiny", line 111, in get_crt                    
    account, code, acct_headers = _send_signed_request(directory['newAccount'], reg_payload, "Error registering")
KeyError: 'newAccount
</pre>

@egon0 found that this is an issue with the actual tiny-acme code. Telling the debops.pki role to use the tiny-acme version "4ed13950c0" fixes this issue.
<pre>pki_acme_tiny_version: '4ed13950c0'</pre>

**Comment by isaiaholoyede** [comment]
I have the same issue. How can I fix this?

**Comment by drybjed** [comment]
You could remove the installed `acme-tiny` script and git repository, and set the above variable in the Ansible inventory. The next time you run `debops.pki` on a host, Ansible will download an older `acme-tiny` release which should work for now.

**Comment by drybjed** [comment]
This issue should now be fixed in the [DebOps monorepo](https://github.com/debops/debops/) via https://github.com/debops/debops/pull/250.

**Comment by isaiaholoyede** [comment]
@drybjed I got a different error when after I tried again... 

$ cat /etc/pki/realms/realms/<domain>/acme/error.log   

Parsing account key...
Parsing CSR...
Found domains: rccgoha.org, www.rccgoha.org
Getting directory...
Directory found!
Registering account...
Traceback (most recent call last):
  File "/usr/local/lib/pki/acme-tiny", line 197, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/pki/acme-tiny", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/local/lib/pki/acme-tiny", line 111, in get_crt
    account, code, acct_headers = _send_signed_request(directory['newAccount'], reg_payload, "Error registering")
TypeError: string indices must be integers

**Comment by drybjed** [comment]
@isaiaho Did you remove the existing PKI realm directory entirely? Can you show the contents of `/etc/pki/realms/rccgoha.org/config/realm.conf`?

**Comment by isaiaholoyede** [comment]
@drybjed This is now fixed. I deleted /etc/pki/realms/ and redeployed. Thank you very much.
