### ISSUE TITLE
Prepare debops.pki environment: Failed to template ... pki_env_secret_directories.j2

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-pki#39]
Then installing a fresh system, I get this error: (line-breaks and ellipsis by me)
```
TASK: [debops.pki/env | Prepare debops.pki environment] *********************** 
fatal: [server] => Failed to template
{{ lookup("template", "lookup/pki_env_secret_directories.j2") | from_yaml }}:
unable to read [....]/debops.pki/env/tasks/lookup/pki_env_secret_directories.j2
```

The requested file exists  in `debops.pki/env/templates/lookup/` (templates, not tasks)

Using current HEAD (279905a47).

**Comment by drybjed** [comment]
Are you using Ansible 2.0+? The older version is looking for templates in `files/` instead of `templates/`.

**Comment by htgoebel** [comment]
Thanks for the quick response. I was using 1.9.4.
