### ISSUE TITLE
Make dependency assertions optional

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-pki#62]
Just got an [issue](https://github.com/carlalexander/debops-wordpress/issues/78) based on #61. I already had a workaround in place to disable certificate authority generation and thus bypass the bash requirement for macOS. I don't want to force anyone to update bash when we don't need it for [simpler setups](https://github.com/debops/ansible-pki/issues/42) like mine.

Are we ok with disabling this if we don't need to run the local script?

**Comment by drybjed** [comment]
You are right, if local Certificate Authority is not present, the `pki-authority` script doesn't need to be run and `bash` version should be irrelevant. The check should be omitted if `pki_authorities` list is empty.
