### ISSUE TITLE
Error with pki-realm script

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-pki#65]
Getting this error from `pki-realm`:

```
/usr/local/lib/pki/pki-realm: line 573: selfsigned/gnutls.conf: No such file or directory
```

I think it's because it's running on an already created PKI domain before the selfsigned changes. The directory doesn't exist so it can't find the file. I tried looking at the script to see how it was doing, but couldn't find where you call `create_gnutls_config`.

**Comment by drybjed** [comment]
That would be correct. Can you check if it works if you create the `selfsigned` directory in that specific realm?

**Comment by ypid** [comment]
@carlalexander drybjed is doing some "advanced" things here :wink: Try searching for `/create_[^\s]*_config/`

**Comment by carlalexander** [comment]
Going to close this since I don't remember this issue and I haven't seen it in a while. I'll reopen if I see it.
