### ISSUE TITLE
Docs: Add example for ACME standard cases

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-pki#83]
The docs to ACME support contain an example for "I want a certificate for subdomains but domain".

Please include a simple example for the standard case: a host serving several vhosts.

Thanks.

**Comment by ypid** [comment]
Examples are always nice and would also have helped me getting into ACME support. Here is a draft: [Example: Certificate for apex domain and subdomains](https://github.com/ypid/ansible-pki/blob/47ba82266b762e3c608115d9d5fb0127204c4d4a/docs/acme-integration.rst#example-certificate-for-apex-domain-and-subdomains)

@htgoebel Does that resolve the issue?

Included in: #81
